#!/sbin/ext/busybox sh

echo $0 $* >> /dev/null

if [ -f /sbin/recovery-is-running ];
then
    if echo "$*" | grep -q -i "remount";
    then
        REMOUNT=",remount";
    else
        REMOUNT="";
    fi;

    if (echo "$*" | grep -q -i "/system"); then
        busybox mount -t yaffs2 -o rw,noatime,nodiratime,check=no$REMOUNT /dev/block/mtdblock4 /system >> /dev/null 2>&1
    elif (echo "$*" | grep -q -i "/datadata") || (echo "$*" | grep -q -i "/dbdata"); then
        busybox mount -t yaffs2 -o rw,noatime,nodiratime,check=no$REMOUNT /dev/block/mtdblock5 /datadata >> /dev/null 2>&1
        busybox mount -t yaffs2 -o rw,noatime,nodiratime,check=no$REMOUNT /dev/block/mtdblock5 /dbdata >> /dev/null 2>&1
    elif (echo "$*" | grep -q -i "/data"); then
        busybox mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=1$REMOUNT /dev/block/mmcblk0p2 /data >> /dev/null 2>&1
    elif (echo "$*" | grep -q -i "/cache"); then
        busybox mount -t yaffs2 -o rw,noatime,nodiratime,check=no$REMOUNT /dev/block/mtdblock6 /cache >> /dev/null 2>&1
    else
	busybox mount $*
	echo busybox mount $* >> /dev/null
    fi;
else
    busybox mount $*
    echo busybox mount $* >> /dev/null
fi;
