#!/sbin/ext/busybox sh

/sbin/ext/busybox mount -t rootfs -o remount,rw rootfs
ln -s /sbin/recovery /sbin/busybox

mount -t yaffs2 -o rw,noatime,nodiratime /dev/block/mtdblock6 /cache >> /dev/null 2>&1

ln -s /sbin/busybox /sbin/sh

start adbd
stop tvout

if [ -f /cache/recovery/command ];
then
  cp /res/keys-samsung /res/keys
  recovery-samsung
else
  echo 1 > /sbin/recovery-is-running
  recovery
fi;
